### ISSUE TITLE
Class not found exception with SLF4j

### ISSUE THREAD

**Issue by yusufcangurkan** [ryantenney/log4j-redis-appender#9]
Hello,

I'm getting the error below. Where should i put my jar?

---

log4j:ERROR Could not instantiate class [com.ryantenney.log4j.RedisAppender].
java.lang.ClassNotFoundException: com.ryantenney.log4j.RedisAppender
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at org.apache.log4j.helpers.Loader.loadClass(Loader.java:198)
    at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:327)
    at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:124)
    at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:785)
    at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
    at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
    at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
    at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)

**Comment by ad197** [comment]
Hi @yusufcangurkan 
Did you figure out the resolution for this issue?

**Comment by github-liyan** [comment]
spark on yarn ，send log to redis，I'm getting the same error
 i had add pom.xml dependes
@ad197

**Comment by github-liyan** [comment]
@ad197
